
version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn install -DskipTests

  build:
    commands:
      - echo Building the project...
      - mvn package

artifacts:
  files:
    - target/*.jar
 
  
